[package]
name = "brainfuck"
version = "0.1.0"
authors = ["Clemens Wasser <clemens.wasser@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[dependencies]
